name: Build and Deploy React App

on:
  workflow_dispatch:
    inputs:
      aws_account_id:
        description: AWS Account ID
        type: string
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # specify the Node.js version

    - name: Install dependencies
      run: npm install
      working-directory: ivs-livestream-app
    - name: Build React app
      run: |
          REACT_APP_PLAYBACK_URL=${{ secrets.REACT_PLAYBACK_URL }} \
          REACT_APP_INGEST_ENDPOINT=${{ secrets.REACT_APP_INGEST_ENDPOINT }} \
          REACT_APP_AWS_REGION=${{ secrets.REACT_APP_AWS_REGION }} \
          REACT_APP_COGNITO_CLIENT_ID=${{ secrets.REACT_APP_COGNITO_CLIENT_ID }} \
          REACT_APP_COGNITO_IDENTITY_POOL_ID=${{ secrets.REACT_APP_COGNITO_IDENTITY_POOL_ID }} \
          REACT_APP_COGNITO_USER_POOL_ID=${{ secrets.REACT_APP_COGNITO_USER_POOL_ID }} \
          REACT_APP_STREAM_KEY=${{ secrets.REACT_APP_STREAM_KEY }} \
          npm run build
      working-directory: ivs-livestream-app
      env:
        REACT_APP_PLAYBACK_URL: ${{ secrets.REACT_PLAYBACK_URL }}
        REACT_APP_INGEST_ENDPOINT: ${{ secrets.REACT_APP_INGEST_ENDPOINT }}
        REACT_APP_AWS_REGION: ${{ secrets.REACT_APP_AWS_REGION }}
        REACT_APP_COGNITO_CLIENT_ID: ${{secrets.REACT_APP_COGNITO_CLIENT_ID}}
        REACT_APP_COGNITO_IDENTITY_POOL_ID: ${{secrets.REACT_APP_COGNITO_IDENTITY_POOL_ID}}
        REACT_APP_COGNITO_USER_POOL_ID: ${{secrets.REACT_APP_COGNITO_USER_POOL_ID}}
        REACT_APP_STREAM_KEY: ${{secrets.REACT_APP_STREAM_KEY}}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/github-actions-dsl
        aws-region: us-east-1 # replace with your AWS region
    - name: Clear S3 bucket
      run: aws s3 rm s3://ivs-livestream-app-ui --recursive

    - name: Deploy to S3
      run: aws s3 cp ./build/ s3://ivs-livestream-app-ui/ --recursive
      working-directory: ivs-livestream-app
    # ... Clear S3 bucket and deploy steps ...
